### ISSUE TITLE
How to include plugins?

### ISSUE THREAD

**Issue by srigar** [wermerb/trumbowyg-ngx#2]
I want to include trumbowyg plugins like **plugins: ['colors', 'noembed', 'preformatted', 'pasteimage', 'upload']**

**Comment by wermerb** [comment]
Hi!

Since all plugins are self registered all you have to do is add the plugin scripts and css files to your .angular-cli.json

`
"styles": [
        "styles.css",
        "../node_modules/trumbowyg/dist/plugins/colors/ui/trumbowyg.colors.css"
 ],
`

`
      "scripts": [
        "../node_modules/jquery/dist/jquery.js",
        "../node_modules/trumbowyg/dist/trumbowyg.min.js",
        "../node_modules/trumbowyg/dist/langs/hu.min.js",
        "../node_modules/trumbowyg/dist/plugins/colors/trumbowyg.colors.js"
      ]
`
